let state={home:null,projects:[],current:null,files:[],snaps:[],theme:'light'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const current=()=>state.projects.find(p=>p.id===state.current)||null;
function go(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#v-'+v).classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.v===v));$('#title').textContent=({home:'Overview',projects:'Projects',archive:'Archived',files:'Files',history:'History',ai:'AI Workspace',workspace:'Workspace',health:'Health'})[v]}
function modal(html){$('#modal').innerHTML=html;$('#modalBg').classList.add('open')}
function closeModal(){$('#modalBg').classList.remove('open')}
async function load(){const st=await foundry.getSettings();state.theme=st.theme||'light';applyTheme();const info=await foundry.homeInfo();state.home=info.home;state.projects=info.library?.projects||[];$('#homeTop').textContent=state.home?'Home: '+state.home:'No Foundry Home';$('#homeStatus').textContent=state.home?'Connected: '+state.home:'Not connected.';$('#workspacePath').textContent=state.home||'Not connected.';renderProjects();await loadCurrent();renderHealth()}
function applyTheme(){document.documentElement.dataset.theme=state.theme;$('#themeBtn').textContent=state.theme==='light'?'☾ Dark theme':'☀ Light theme'}
async function loadCurrent(){if(!state.current){state.files=[];state.snaps=[];renderFiles();renderSnaps();return}state.files=await foundry.listFiles(state.current);state.snaps=await foundry.listSnapshots(state.current);renderFiles();renderSnaps()}
function renderProjects(){const active=state.projects.filter(p=>p.status!=='archived'),arch=state.projects.filter(p=>p.status==='archived');$('#recent').innerHTML=active.slice(0,6).map(p=>`<div class="row"><b style="flex:1">${esc(p.name)}</b><button class="btn" onclick="openProject('${p.id}')">Open</button></div>`).join('')||'<div class="empty">No projects yet.</div>';$('#projects').innerHTML=active.map(p=>`<div class="row"><b style="flex:1">${esc(p.name)}</b><span class="pill">${esc(p.status)}</span><button class="btn primary" onclick="openProject('${p.id}')">Open</button><button class="btn" onclick="archiveProject('${p.id}')">Archive</button></div>`).join('')||'<div class="empty">No projects yet.</div>';$('#archived').innerHTML=arch.map(p=>`<div class="row"><b style="flex:1">${esc(p.name)}</b><button class="btn" onclick="restoreProject('${p.id}')">Restore</button></div>`).join('')||'<div class="empty">No archived projects.</div>'}
async function openProject(id){state.current=id;await loadCurrent();go('files');renderHealth()}
async function archiveProject(id){await foundry.archiveProject(id);if(state.current===id)state.current=null;await load();go('projects')}
async function restoreProject(id){await foundry.restoreProject(id);await load();go('archive')}
function renderFiles(){$('#files').innerHTML=state.files.length?state.files.map(f=>`<div class="row"><b style="flex:1">${esc(f.name)}</b><span class="mut">${f.size} bytes</span><button class="btn" onclick='previewFile(${JSON.stringify(f.path)})'>View</button></div>`).join(''):'<div class="empty">No working files.</div>'}
async function previewFile(p){const r=await foundry.readFile(p);$('#filePreview').textContent=r.binary?'Binary file — preview unavailable.':r.text.slice(0,50000)}
function renderSnaps(){$('#snapshots').innerHTML=state.snaps.length?state.snaps.map(s=>`<div class="row"><div style="flex:1"><b>${esc(s.message||'Snapshot')}</b><div class="mut">${new Date(s.createdAt).toLocaleString()} · ${s.files.length} file(s)</div></div><button class="btn" onclick="restoreSnap('${s.id}')">Restore</button></div>`).join(''):'<div class="empty">No snapshots yet.</div>'}
async function restoreSnap(id){await foundry.restoreSnapshot(state.current,id);await loadCurrent()}
function renderHealth(){const p=current();$('#health').innerHTML=`<p>${state.home?'<span class="ok">✓</span> Native workspace connected':'<span class="warn">●</span> Choose Foundry Home'}</p><p>${p?'<span class="ok">✓</span> Current project: '+esc(p.name):'No current project'}</p><p>${state.files.length} working file(s)</p><p>${state.snaps.length} snapshot(s)</p><p class="ok">Renderer has no direct filesystem access.</p>`}
async function compile(){const p=current();if(!p)return alert('Open a project first.');const chunks=['FOUNDRY CONTEXT PACKAGE','Project: '+p.name,'FOUNDATION: Human authority; AI output is a proposal, never an overwrite.'];let included=0,excluded=0;for(const f of state.files){const ext=f.name.split('.').pop().toLowerCase();if(['csv','xls','xlsx','ods','tsv'].includes(ext)){excluded++;continue}const r=await foundry.readFile(f.path);if(!r.binary){chunks.push('FILE: '+f.name+'\n'+r.text);included++}}chunks.push('TASK: '+$('#task').value.trim());const prompt=chunks.join('\n\n---\n\n');$('#prompt').value=prompt;$('#receipt').innerHTML=`<p><b>Mode:</b> Manual / Clipboard</p><p><b>Included files:</b> ${included}</p><p><b>Excluded sensitive-by-default:</b> ${excluded}</p>`}
window.openProject=openProject;window.archiveProject=archiveProject;window.restoreProject=restoreProject;window.previewFile=previewFile;window.restoreSnap=restoreSnap;
$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.v));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#themeBtn').onclick=async()=>{state.theme=state.theme==='light'?'dark':'light';applyTheme();await foundry.setSettings({theme:state.theme})};
$('#chooseHome').onclick=async()=>{const h=await foundry.chooseHome();if(h)await load()};$('#openHome').onclick=()=>foundry.openHome();$('#scanHome').onclick=async()=>{await foundry.scanHome();await load()};
function openNewProject(){modal('<h2>Create project</h2><input id="newName" class="input" placeholder="Project name"><div class="modal-actions"><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="create">Create</button></div>');$('#cancel').onclick=closeModal;$('#create').onclick=async()=>{try{await foundry.createProject($('#newName').value);closeModal();await load();go('projects')}catch(e){alert(e.message)}}}
$('#newProjectTop').onclick=openNewProject;$('#importFiles').onclick=async()=>{if(!state.current)return alert('Open a project first.');await foundry.importFiles(state.current);await loadCurrent()};$('#snapshot').onclick=async()=>{if(!state.current)return alert('Open a project first.');await foundry.createSnapshot(state.current);await loadCurrent()};$('#backupAll').onclick=async()=>alert('Backup created:\n'+await foundry.backupWhole());
$('#compile').onclick=compile;$('#copyPrompt').onclick=()=>foundry.copyText($('#prompt').value);$('#pasteResult').onclick=async()=>$('#result').value=await foundry.pasteText();$('#importResult').onclick=async()=>{const t=await foundry.importAIResult();if(t!==null)$('#result').value=t};$('#saveRun').onclick=()=>{if(!$('#result').value.trim())return alert('Paste or import a result first.');alert('Manual result captured. Persistent run storage is the next sub-pass before safe-edit proposals.')};$('#modalBg').onclick=e=>{if(e.target===$('#modalBg'))closeModal()};load();
